embeddings:
  # TorchText GloVe (automatic download)
  torchtext_glove:
    enabled: true
    name: "6B"  # Options: "6B", "42B", "840B", "twitter.27B"
    dim: 100    # Options for 6B: 50, 100, 200, 300
    cache: ".vector_cache"
  
  # TorchText FastText (automatic download)
  torchtext_fasttext:
    enabled: true
    language: "en"  # Options: "en", "simple"
    cache: ".vector_cache"
  
  # Legacy: Local GloVe file
  glove:
    enabled: false
    path: "models/glove.6B.100d.txt"
    dimensions: 100
  
  # Legacy: Local Word2Vec file
  word2vec:
    enabled: false
    path: "models/word2vec.model"
    vector_size: 300
    binary: true

visualization:
  method: "tsne"  # Options: "tsne", "pca"
  tsne:
    perplexity: 30
    n_iter: 1000
    random_state: 42
  pca:
    n_components: 2
  figure:
    width: 10
    height: 8
    dpi: 100

api:
  host: "0.0.0.0"
  port: 8000
  title: "Word Embedding Analyzer API"
  description: "API for word similarity and analogy tasks using Word2Vec and GloVe"
  version: "1.0.0"

app:
  title: "Word Embedding Analyzer"
  page_icon: "📊"
  layout: "wide"

cache:
  enabled: true
  max_size: 1000